apiVersion: v1
kind: ConfigMap
metadata:
  name: charts-api-config
  namespace: user-charts
data:
  rancher-url: "https://rancher.nsogroup.com"
  rancher-cluster-id: "REPLACE_WITH_CLUSTER_ID"
  artifactory-helm-repo-url: "https://artifactory.nsogroup.com/artifactory/devops-helm-release-local"
