apiVersion: v1
kind: ConfigMap
metadata:
  name: charts-api-config
  namespace: user-charts
data:
  argocd-server-url: "https://users-argocd.devops.nsogroup.com"
  artifactory-helm-repo-url: "https://artifactory.nsogroup.com/artifactory/devops-helm-release-local"
