apiVersion: v1
kind: Secret
metadata:
  name: charts-api-secrets
  namespace: user-charts
type: Opaque
stringData:
  rancher-token: "REPLACE_WITH_RANCHER_SA_TOKEN"
  artifactory-username: ""
  artifactory-password: ""
  ldap-username: "REPLACE_WITH_LDAP_SVC_ACCOUNT"
  ldap-password: "REPLACE_WITH_LDAP_PASSWORD"
